services:
  mysqldb:
    image: mysql:8.0.33
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./sql/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/data_load.sql:/docker-entrypoint-initdb.d/2.sql"
      - "./scripts/user.sql:/docker-entrypoint-initdb.d/3.sql"
      - mysql-data:/var/lib/mysql

    networks:
      - nodejs-mysql-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 10
      interval: 3s
      timeout: 30s

  app:
    depends_on:
      - mysqldb
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQL_USER
      - DB_PASSWORD=$MYSQL_PASSWORD
      - DB_NAME=$MYSQL_DATABASE
      - DB_PORT=$MYSQL_DOCKER_PORT
    networks:
      - nodejs-mysql-network
    stdin_open: true
    tty: true

volumes:
  mysql-data:

networks:
  nodejs-mysql-network:
    name: nodejs-mysql-network
